### PR TITLE
Include mlr3

### PR DESCRIPTION
**Pull request by jakob-r**
I mashed up some things to mention mlr3. I don't know if we have to mention mlr3 in the sign up process because most mlr3 people will probably join "by invitation".

Hope that this is kind of how we intended it to be. @pat-s @berndbischl

### CODE REVIEW

**Comment by pat-s** [comment]
Ping Bernd multiple times to get confirmation so we can merge soon :)

**Comment by berndbischl** [comment]
the text looks fine to me

**Comment by berndbischl** [comment]
is it possible to see the rendered page somehow?
@joaquinvanschoren

**Comment by jakob-r** [comment]
```
git clone git@github.com:jakob-r/meet.git
cd meet
open index.html
```

**Comment by berndbischl** [comment]
ok thx! i could render it. what is a bit weird is that our section is now completely separate from the oml hackathon (which also contains all of the "how to get there info")

shall we somehow merge the 2 texts?`i dont want to overengineer this though

**Comment by joaquinvanschoren** [comment]
Looks good. To answer Bernd's comments, maybe update the text at the bottom to cover both OpenML and MLR:
* Replace "contribute to the platform, or work on it directly" to something like "contribute to OpenML or MLR".
* Remove the line about travel support.

**Comment by jakob-r** [comment]
I applied @joaquinvanschoren suggestions. I think mentioning mlr3 in the location part is sufficient to indicate that they are not separate events.

**Comment by berndbischl** [comment]
Merge it now we can adapt it later if problems occur

**Pull request merged**
